"""initial schema

Revision ID: fa717c588605
Revises: 
Create Date: 2026-05-01 14:09:28.934092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa717c588605'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('stadium', sa.String(length=120), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clubs_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_clubs_name'), ['name'], unique=True)

    op.create_table('competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competitions_name'), ['name'], unique=True)

    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year_label', sa.String(length=20), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_year >= start_year', name='ck_season_year_range'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seasons_year_label'), ['year_label'], unique=True)

    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(length=80), nullable=True),
    sa.Column('position', sa.String(length=40), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('current_club_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_club_id'], ['clubs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_current_club_id'), ['current_club_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_first_name'), ['first_name'], unique=False)
        batch_op.create_index('ix_players_full_name', ['last_name', 'first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_nationality'), ['nationality'], unique=False)

    op.create_table('player_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Integer(), nullable=True),
    sa.Column('preferred_foot', sa.String(length=10), nullable=True),
    sa.Column('jersey_number', sa.Integer(), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("preferred_foot IS NULL OR preferred_foot IN ('Left', 'Right', 'Both')", name='ck_profile_foot'),
    sa.CheckConstraint('height_cm IS NULL OR height_cm BETWEEN 100 AND 250', name='ck_profile_height'),
    sa.CheckConstraint('jersey_number IS NULL OR jersey_number BETWEEN 1 AND 99', name='ck_profile_jersey'),
    sa.CheckConstraint('weight_kg IS NULL OR weight_kg BETWEEN 30 AND 200', name='ck_profile_weight'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id')
    )
    op.create_table('player_season_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('appearances', sa.Integer(), nullable=False),
    sa.Column('minutes_played', sa.Integer(), nullable=False),
    sa.Column('yellow_cards', sa.Integer(), nullable=False),
    sa.Column('red_cards', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('appearances >= 0', name='ck_stats_appearances_positive'),
    sa.CheckConstraint('assists >= 0', name='ck_stats_assists_positive'),
    sa.CheckConstraint('goals >= 0', name='ck_stats_goals_positive'),
    sa.CheckConstraint('minutes_played >= 0', name='ck_stats_minutes_positive'),
    sa.CheckConstraint('red_cards >= 0', name='ck_stats_red_positive'),
    sa.CheckConstraint('yellow_cards >= 0', name='ck_stats_yellow_positive'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season_id', 'competition_id', name='uq_player_season_competition')
    )
    with op.batch_alter_table('player_season_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_season_stats_club_id'), ['club_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_season_stats_competition_id'), ['competition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_season_stats_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_season_stats_season_id'), ['season_id'], unique=False)
        batch_op.create_index('ix_stats_player_season', ['player_id', 'season_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_season_stats', schema=None) as batch_op:
        batch_op.drop_index('ix_stats_player_season')
        batch_op.drop_index(batch_op.f('ix_player_season_stats_season_id'))
        batch_op.drop_index(batch_op.f('ix_player_season_stats_player_id'))
        batch_op.drop_index(batch_op.f('ix_player_season_stats_competition_id'))
        batch_op.drop_index(batch_op.f('ix_player_season_stats_club_id'))

    op.drop_table('player_season_stats')
    op.drop_table('player_profiles')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_nationality'))
        batch_op.drop_index(batch_op.f('ix_players_last_name'))
        batch_op.drop_index('ix_players_full_name')
        batch_op.drop_index(batch_op.f('ix_players_first_name'))
        batch_op.drop_index(batch_op.f('ix_players_current_club_id'))

    op.drop_table('players')
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seasons_year_label'))

    op.drop_table('seasons')
    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competitions_name'))

    op.drop_table('competitions')
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clubs_name'))
        batch_op.drop_index(batch_op.f('ix_clubs_country'))

    op.drop_table('clubs')
    # ### end Alembic commands ###
